using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using System.Text.Json;
using System.Text.Json.Nodes;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.Text;

namespace GoodGlam.SourceGen;

/// <summary>
/// Generates the strongly-typed <c>StringCatalog</c> tree from the embedded English string template
/// (<c>Strings.en.jsonc</c>), so contributors edit only the template while call sites keep
/// compile-time-safe access via <c>Loc.Strings.*</c>. The shape maps to C# as: a string leaf becomes a
/// <c>string</c> property, an array of strings becomes an <c>IReadOnlyList&lt;string&gt;</c> property,
/// and a nested object becomes a nested <c>XxxStrings</c> group class. The template is JSONC (comments
/// and trailing commas allowed).
/// </summary>
[Generator(LanguageNames.CSharp)]
public sealed class StringCatalogGenerator : IIncrementalGenerator
{
    private const string TemplateFileName = "Strings.en.jsonc";
    private const string Namespace = "GoodGlam.Localization";
    private const string RootTypeName = "StringCatalog";

    private static readonly HashSet<string> ManualRootNodes = new() { "slots" };

    private static readonly DiagnosticDescriptor TemplateError = new(
        id: "GGLOC001",
        title: "Invalid GoodGlam string template",
        messageFormat: "Could not generate the string catalog from '{0}': {1}",
        category: "GoodGlam.Localization",
        defaultSeverity: DiagnosticSeverity.Error,
        isEnabledByDefault: true);

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var templates = context.AdditionalTextsProvider
            .Where(static text => Path.GetFileName(text.Path) == TemplateFileName)
            .Select(static (text, ct) => (text.Path, Content: text.GetText(ct)?.ToString()));

        context.RegisterSourceOutput(templates, static (spc, template) =>
        {
            if (string.IsNullOrEmpty(template.Content))
            {
                spc.ReportDiagnostic(Diagnostic.Create(TemplateError, Location.None, template.Path, "the file was empty."));
                return;
            }

            JsonNode? root;
            try
            {
                // JSONC: skip // and /* */ comments and tolerate trailing commas, matching the runtime
                // StringCatalog.JsonOptions so the same template parses identically at build and run time.
                root = JsonNode.Parse(
                    template.Content!,
                    nodeOptions: null,
                    documentOptions: new JsonDocumentOptions
                    {
                        CommentHandling = JsonCommentHandling.Skip,
                        AllowTrailingCommas = true,
                    });
            }
            catch (JsonException ex)
            {
                spc.ReportDiagnostic(Diagnostic.Create(TemplateError, Location.None, template.Path, ex.Message));
                return;
            }

            if (root is not JsonObject rootObject)
            {
                spc.ReportDiagnostic(Diagnostic.Create(
                    TemplateError, Location.None, template.Path, "the top-level JSON value must be an object."));
                return;
            }

            string source;
            try
            {
                source = Emit(rootObject);
            }
            catch (InvalidTemplateException ex)
            {
                spc.ReportDiagnostic(Diagnostic.Create(TemplateError, Location.None, template.Path, ex.Message));
                return;
            }

            spc.AddSource("StringCatalog.g.cs", SourceText.From(source, Encoding.UTF8));
        });
    }

    private static string Emit(JsonObject root)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine($"namespace {Namespace};");
        sb.AppendLine();

        // Tracks every generated type name so two different template paths that Pascalize to the same
        // type (e.g. a root key "fooBar" and a nested "foo"->"bar", both -> FooBarStrings) fail with a
        // clear diagnostic instead of emitting two same-named classes that don't compile.
        var typeNames = new HashSet<string> { RootTypeName };

        EmitType(sb, RootTypeName, root, isRoot: true, pathPascal: string.Empty, typeNames);
        return sb.ToString();
    }

    private static void EmitType(
        StringBuilder sb, string typeName, JsonObject obj, bool isRoot, string pathPascal, HashSet<string> typeNames)
    {
        var nested = new List<(string TypeName, JsonObject Obj)>();

        // Tracks member names within this one object so two keys that Pascalize to the same C# member
        // (e.g. "foo" and "Foo") fail with a clear diagnostic instead of emitting a duplicate property.
        var memberNames = new HashSet<string>();

        sb.AppendLine("/// <summary>Generated from Strings.en.jsonc. Do not edit; edit the template instead.</summary>");
        sb.AppendLine(isRoot
            ? $"public sealed partial class {RootTypeName}"
            : $"public sealed class {typeName}");
        sb.AppendLine("{");

        foreach (var member in obj)
        {
            var key = member.Key;
            if (isRoot && ManualRootNodes.Contains(key))
                continue;

            var propName = Pascalize(key);

            // The template is edited by hand (and translated), so guard the "edit only the template"
            // promise: a key that doesn't map to a valid C# identifier (a hyphen, space, leading digit,
            // etc.) would otherwise emit uncompilable code with a cryptic error in the generated file.
            // Fail here with a clear diagnostic that names the offending key instead.
            if (!SyntaxFacts.IsValidIdentifier(propName))
                throw new InvalidTemplateException(
                    $"Key '{key}' maps to C# member '{propName}', which is not a valid identifier. " +
                    "Template keys must form valid C# identifiers (letters, digits, and underscore; not " +
                    "starting with a digit).");

            // Two keys in the same object that Pascalize to the same member (e.g. "foo" and "Foo") would
            // emit a duplicate property; fail here naming the collision instead.
            if (!memberNames.Add(propName))
                throw new InvalidTemplateException(
                    $"Key '{key}' maps to C# member '{propName}', which collides with another key in the " +
                    "same object. Template keys must Pascalize to distinct C# members.");

            switch (member.Value)
            {
                case JsonValue when IsString(member.Value):
                    sb.AppendLine($"    public string {propName} {{ get; init; }} = \"\";");
                    break;

                case JsonArray array:
                    EnsureStringArray(key, array);
                    sb.AppendLine(
                        $"    public global::System.Collections.Generic.IReadOnlyList<string> {propName} " +
                        "{ get; init; } = global::System.Array.Empty<string>();");
                    break;

                case JsonObject childObject:
                    var childTypeName = pathPascal + propName + "Strings";
                    if (!typeNames.Add(childTypeName))
                        throw new InvalidTemplateException(
                            $"Key '{key}' produces generated type '{childTypeName}', which collides with " +
                            "another generated type. Rename one of the colliding template keys.");
                    sb.AppendLine($"    public {childTypeName} {propName} {{ get; init; }} = new();");
                    nested.Add((childTypeName, childObject));
                    break;

                default:
                    throw new InvalidTemplateException(
                        $"Key '{key}' must be a string, an array of strings, or an object.");
            }
        }

        sb.AppendLine("}");
        sb.AppendLine();

        foreach (var child in nested)
            EmitType(sb, child.TypeName, child.Obj, isRoot: false, pathPascal: TypeToPath(child.TypeName), typeNames);
    }

    private static void EnsureStringArray(string key, JsonArray array)
    {
        foreach (var item in array)
        {
            if (!IsString(item))
                throw new InvalidTemplateException($"Array '{key}' must contain only strings.");
        }
    }

    private static bool IsString(JsonNode? node)
        => node is JsonValue value && value.GetValueKind() == JsonValueKind.String;

    /// <summary>The Pascal path a nested type carries forward for naming its own children (its type name minus the "Strings" suffix).</summary>
    private static string TypeToPath(string typeName)
        => typeName.EndsWith("Strings", System.StringComparison.Ordinal)
            ? typeName.Substring(0, typeName.Length - "Strings".Length)
            : typeName;

    /// <summary>Upper-cases the first character of a camelCase JSON key to form a PascalCase C# identifier.</summary>
    private static string Pascalize(string key)
    {
        if (key.Length == 0)
            return key;

        return char.ToUpperInvariant(key[0]) + key.Substring(1);
    }

    private sealed class InvalidTemplateException : System.Exception
    {
        public InvalidTemplateException(string message) : base(message)
        {
        }
    }
}
